bjoerne_my_albums_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: BjoerneMyAlbumsBundle:Default:index }

my_albums_controller:
    resource: "@BjoerneMyAlbumsBundle/Controller"
    type:     annotation